### PR TITLE
Main cases covered. class, typed and anonymous

### PR DESCRIPTION
**Pull request by 0b1kn00b**
Includes dependency on tink_macro and utest. Check src/test/haxe/LenseTest.hx for usage.

I think I've typed the variables properly so that they use the abstract version of Lense.

### CODE REVIEW

**Comment by sledorze** [comment]
That's quite a big one, so I'll take some time to review and validate it (I'm OFF on the road tomorrow).

However, several things on the implementation side ;
- Please use Option<T> instead of Null<T> as much as possible (I've seen some place where NPE could arise).
- Try to reduce the number of new packages ( 'ah' / 'stx' ).
- I'm not sure about the uuid approach (I would prefer an idempotent solution - I'm thinking about compiler cache).
- What's the thing about 'Modules' ? also Module related tests that are commented and don't pass?

Also, if you can remove the nodejs from the build; it would be nice as I don't want to force this dependency - using Neko for that purpose removes it.

Thanks Laurence!

**Comment by 0b1kn00b** [comment]
The uuid approach is while I figure out what goes on with the "follow" function in Context, and how to identify exactly what type is being dealt with, without hitting weirdness. I'd like a cache of previously used `Lensers` but with Anonymous Types I'm not sure it's worth the hassle to parse the type for an eq with what is already there.

Module was trying to figure out what's going on with `name`, `pack` and `module`. Turns out `module` is the package name in `String` format plus the name of the module, so it's not necessary to use `pack` but you have to find out if `BaseType.name` is the same as the last dot delimited value of `BaseType.module` to compose a correct path given that (it seems like)<sigh> even if you use the correct `pos` value to place the new type declaration in the same module as the lensed type, it doesn't pick up on the type imports, and throws an error.
A class in module `TEST_MODULE` could be `test_package.TEST_MODULE` if the module name and class name coincide, or `test_package.TEST_MODULE.TestClass` if they don't, which is why there is some utility functions introduced. (stx and ah are the namespaces I use, I'll support those)

Thinking about it last night, there could be some problems with.
a) Type name aliasing, which is why there is some faffing with `try..catch` blocks
b) The behavior of sub classes is currently undefined, so that needs testing.

I disagree with you on Option vs Null on the basis that encoding enumerations on the wire **requires** a solid abstraction of a relation and types of some sort, of which there are so many, and differently defined. It doesn't seem like solid ground to me at all given json graph and jsonld etc etc. If I can find a robust mitigation, would that be alright? 

I was thinking of renaming `Lensers` as `Lenox`.

I'll remove as a dependency nodejs post-haste.

**Comment by 0b1kn00b** [comment]
Y u no respond. I've pulled nodejs out, and fixed the odd bug. No breakages with the tests so far.

**Comment by sledorze** [comment]
Hi Laurence, thanks for the hard work, it will be a nice addition.
However I think we misunderstood on the Option / Null thing; I was refering to the usage of Null<..> type in your PR.
I see in the actual code that some null access could arise (that correspond to some unhandled cases).
We should never error with null access as this is misleading for the library user but with graceful messages.
Please check these functions:
getBaseType
getAnonType
getFullPath

and in build/Lense, the functions:
build 
processSubType

Those functions should use/return Options (or another type safe disjunction in order to thread the cases in caller sites) or error with a meaningful message.

I want to have nulls to disappear as soon as possible in the code base, thanks for respecting this principle ;)

**Comment by sledorze** [comment]
sorry I've hit enter too early.. :)

and in build/Lense, the functions:
build 
processSubType

Those functions should use/return Options (or another type safe disjunction in order to thread the cases in caller sites) or error with a meaningful message.

I want to have nulls to disappear as soon as possible in the code base, thanks for respecting this principle ;)

**Comment by 0b1kn00b** [comment]
[Would this do?](https://github.com/0b1kn00b/stx_maybe)

**Comment by sledorze** [comment]
@0b1kn00b 
I'm concerned about type safety (and not too much specific additional code).
It is ok for me :)

Let's make our macro as type/refactor safe as possible!

**Comment by 0b1kn00b** [comment]
Ok, had some regressions with Maybe because of 3.1.\* developments, but have cleared that up(afaik) and updated the haxelib . Still haven't explicitly done anything about lensing dynamics (I think it can be done)

**Comment by sledorze** [comment]
@0b1kn00b oh god; can you please re read that one ? https://github.com/sledorze/Lenox/pull/4#issuecomment-160480817

The maybe thing is for the functions used in the macros referred to in that comment; not the lenses functions themselves..

**Comment by 0b1kn00b** [comment]
If you'd like to compile and run the tests, to see that it's not just my machine where it works, that would be cool, and I'll fix the internal api.

**Comment by sledorze** [comment]
haxe build.hxml          

assertations: 5
successes: 5
errors: 0
failures: 0
warnings: 0
execution time: 0

results: ALL TESTS OK (success: true)
LenseTest
  testAnonymousLenseBuild: OK .
  testClassLenseBuild: OK .
  testDynamicLeaf: OK .
  testLenseComposition: OK .
  testTypeLenseBuild: OK .

**Comment by 0b1kn00b** [comment]
Sweet, thanks.

**Comment by 0b1kn00b** [comment]
ooh. Thanks

**Pull request merged**
